#+TITLE: AD57X1R
#+AUTHOR: Sergeu Todorov
#+EMAIL: alloa@mail.ru

* Library Information
  - Name :: AD57x1R
  - Version :: 1.0.0
  - URL :: https://github.com/Sergsan79/AD57x1R
  - Author :: Sergey Todorov
  - Email :: alloa@mail.ru
  
For ARDUINO.
Provides an SPI based interface to the AD5721R, and the AD5761R Quad 12-/16-Bit Unipolar, Voltage Output DACs

* Information
  - AD57x1R(uint8_t Part_DAC, int ALERT, int SYNC, int RESET, int CLEAR, int LDAC); :: // INIT
  - int32_t AD57x1R_write_control_register (struct control_register dev); :: // Write to control register ADD 04
  - int32_t AD57x1R_write_input_register( uint16_t dac_data); :: // Write to input register (no update) ADD 01  
  - int32_t AD57x1R_write_update_dac_register( uint16_t dac_data); :: // Write and update DAC register ADD 03
  - int32_t AD57x1R_update_dac_register(); :: // Update DAC register from input register ADD 02
  - AD57x1R_update_dac_LDAC(); :: // pin LDAC
  - int32_t AD57x1R_software_data_reset(); :: // Software data reset ADD 07
  - int32_t AD57x1R_set_daisy_chain_en_dis(bool en_dis); :: // Disable daisy-chain functionality ADD 09
  - int32_t AD57x1R_register_readback(uint8_t reg); :: // Readback input register ADD10, Readback DAC      register ADD 11, Readback   - control register ADD 12.
  - int32_t AD57x1R_software_full_reset(); :: // Software full reset ADD 15
  - bool AD57x1R_get_brownout_condition(); :: // Brownout condition. The BO bit is reset at every control register write.                                                                                    
  - bool AD57x1R_get_short_circuit_condition(); :: // Short-circuit condition. The SC bit is reset at every control register write.
                                                                                    
